export const START_AUTH = 'START_AUTH';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FAIL = 'SIGN_UP_FAUL';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const REQUEST_TOKEN = 'REQUEST_TOKEN';


export const START_PROCESSS_CATEGORY = 'START_PROCESS_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const PROCESS_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';


export const START_PROCESSS_PRODUCT = 'START_PROCESS_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PROCUCT_SUCCESS';
export const PROCESS_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';